spring:
  h2:
    console:
      enabled: true
      path: /h2

  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:h2:tcp://localhost/~/payment
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
